### ISSUE TITLE
Add StableHLO to TTIR conversion for logistic OP

### ISSUE THREAD

**Issue by mrakitaTT** [tenstorrent/tt-mlir#1026] opened 2024-10-23 21:05 UTC
Add support for StableHLO to TTIR conversion for `logistic` OP, lower to ttnn and add unit tests to tt-torch and tt-xla.

Can be lowered to `ttnn.sigmoid`.

**Comment by kmitrovicTT** [comment] 2024-10-24 13:18
Duplicate of https://github.com/tenstorrent/tt-mlir/issues/970

**Closed** 2024-12-10 17:18 UTC
Labels: MLIR Ops, Priority Model Op Bringup
