### ISSUE TITLE
querying system descriptor on n300 errors

### ISSUE THREAD

**Issue by ttdloke** [tenstorrent/tt-mlir#246] opened 2024-07-29 17:28 UTC
Traceback (most recent call last):
  File "/opt/ttmlir-toolchain/venv/bin/ttrt", line 8, in <module>
    sys.exit(main())
  File "/opt/ttmlir-toolchain/venv/lib/python3.8/site-packages/ttrt/__init__.py", line 271, in main
    args.func(args)
  File "/opt/ttmlir-toolchain/venv/lib/python3.8/site-packages/ttrt/__init__.py", line 195, in query
    print(ttrt.runtime.get_current_system_desc()[0].as_json())
IndexError: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

**Comment by tapspatel** [comment] 2024-07-29 19:47
unable to reproduce issue on latest main. test command
```
ttrt query --system-desc
```

Closing issue. Please reopen if issue occurs

**Closed by tapspatel** 2024-07-29 19:47 UTC
Labels: bug, ttrt, flatbuffer
