### ISSUE TITLE
[StableHLO] Reduce op failure

### ISSUE THREAD

**Issue by mmanzoorTT** [tenstorrent/tt-mlir#848] opened 2024-09-30 17:53 UTC
StableHLO `reduce` op is failing due to issues with [`constant` op](https://github.com/tenstorrent/tt-mlir/issues/847)

A sample test case can be found in [tt-xla PR](https://github.com/tenstorrent/tt-xla/pull/15)

**Comment by nsmithtt** [comment] 2024-10-09 11:53
Not sure what the issue is from the description.  Not sure which component to send it to, can you add more context?

**Comment by mmanzoorTT** [comment] 2024-10-10 13:19
`jnp.max(array)` is lowered to 
```
    %0 = stablehlo.constant dense<0xFF800000> : tensor<f32>
    %1 = stablehlo.reduce(%arg0 init: %0) applies stablehlo.maximum across dimensions = [0, 1] : (tensor<128x784xf32>, tensor<f32>) -> tensor<f32>
```

Similarly, `jnp.sum(array)` is lowered to 
```
    %cst = stablehlo.constant dense<0xFF800000> : tensor<f32>
    %0 = stablehlo.reduce(%arg0 init: %cst) applies stablehlo.maximum across dimensions = [0, 1] : (tensor<2x1xf32>, tensor<f32>) -> tensor<f32>
```

`stablehlo.reduce` requires a scalar constant for initialization and scalar constant support is in progress. So `stablehlo.reduce` is blocked. We have stablehlo to TTIR conversion for stablehlo.reduce but end-to-end tests (using jax) fails due to issues with scalar constant.

**Comment by mmanzoorTT** [comment] 2024-10-10 21:24
TTNN has `ttnn.max` and `ttnn.sum` ops which corresponds to `stablehlo.reduce` op. TTNN version does not require initialization constant and it gets remove as dead code. so scalar constant is not an issue here. 
`stablehlo.reduce` conversion has few bugs which are fixed in #899

**Comment by uazizTT** [comment] 2024-10-11 03:03
This seems to be a duplicate of #805

**Comment by mrakitaTT** [comment] 2024-12-20 23:38
Closing as a duplicate of #805

**Closed by mrakitaTT** 2024-12-20 23:38 UTC
