### ISSUE TITLE
Reshape fails with non-tile-dim aligned shapes

### ISSUE THREAD

**Issue by chandrasekaranpradeep** [tenstorrent/tt-mlir#679] opened 2024-09-13 12:54 UTC
## **Summary**
Embedding op fails when TILE_LAYOUT is used.

## Details
The `ttnn::embedding` fails with `TILE_LAYOUT` when the input tensor of shape `(1, 12)` is passed to reshape op with new_shape of `(1, 1, 1, 12)`. 

The reshape op, new_height(1) and new_width(12) are not moduli of `ttnn::TILE_SIZE` which throws `Unable to reshape a tensor in TILE_LAYOUT to non-tile height and width! Please convert the tensor to ROW_MAJOR_LAYOUT first`.

## TTIR
```
module @Embedding attributes {tt.system_desc = #tt.system_desc<[{arch = <wormhole_b0>, grid = 8x8, l1_size = 1499136, num_dram_channels = 12, dram_channel_size = 1073741824, noc_l1_address_align_bytes = 16, pcie_address_align_bytes = 32, noc_dram_address_align_bytes = 32, l1_unreserved_base = 0, erisc_l1_unreserved_base = 0, dram_unreserved_base = 0, dram_unreserved_end = 1073741824, physical_cores = {worker = [(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7)] dram = [(8, 0), (9, 0), (10, 0), (8, 1), (9, 1), (10, 1), (8, 2), (9, 2), (10, 2), (8, 3), (9, 3), (10, 3)]}, supported_data_types = [<f32>, <f16>, <bf16>, <bfp_f8>, <bfp_bf8>, <bfp_f4>, <bfp_bf4>, <bfp_f2>, <bfp_bf2>, <u32>, <u16>, <u8>], supported_tile_sizes = [(4 x 16), (16 x 16), (32 x 16), (4 x 32), (16 x 32), (32 x 32)]}], [0], [3 : i32], [<0, 0, 0, 0>]>} {
  func.func @forward(%arg0: tensor<1x12xi8> {ttir.name = "input"}, %arg1: tensor<32000x3200xf32> {ttir.name = "embedding.weight"}) -> tensor<1x12x3200xf32> {
    %0 = tensor.empty() : tensor<1x12x3200xf32>
    %1 = "ttir.embedding"(%arg1, %arg0, %0) <{operand_constraints = [#tt.operand_constraint<dram|l1|scalar|tile|none_layout|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>, #tt.operand_constraint<dram|l1|scalar|tile|none_layout|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>, #tt.operand_constraint<dram|l1|scalar|tile|none_layout|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device|any_device_tile|l1_block_sharded>]}> : (tensor<32000x3200xf32>, tensor<1x12xi8>, tensor<1x12x3200xf32>) -> tensor<1x12x3200xf32>
    return %1 : tensor<1x12x3200xf32>
  }
} 
```
        
## **Test cases in TT-forge-fe**
```
git checkout pchandrasekaran/embedding
pytest forge/test/mlir/test_ops.py::test_embedding -vss

## **Additional details**
In tt-mlir repo, in runtime,  the input (shape: {1, 12}) and weight (shape: {32000, 3200}) ttnn tensor are passed to **runProgram** function with `ROW_MAJOR_LAYOUT`. Then when **ToMemoryConfigOp**(i.e `::tt::target::ttnn::ToMemoryConfigOp`) is executed, the input and weight ttnn tensor are converted from `ROW_MAJOR_LAYOUT` to `TILE_LAYOUT` using **tilize** function because of the input and weight ttnn tensors are not of type **BFLOAT16** (i.e `::ttnn::DataType::BFLOAT16`)  and both tensors are in **borrowed** or **owned** host storage (i.e `::tt::tt_metal::StorageType::BORROWED or ::tt::tt_metal::StorageType::OWNED`). 

Further more, the function **handleToDramMemoryConfigOp** which leads to` Unable to reshape a tensor in TILE_LAYOUT to non-tile height and width! Please convert the tensor to ROW_MAJOR_LAYOUT first` issue in the reshape function called from `ttnn.embedding` of **EmbeddingOperation** namespace invoke function if the reshape op new_height and new_width with tile padded are not modulus of **ttnn::TILE_SIZE**.

**Comment by nvukobratTT** [comment] 2024-09-13 14:44
@sdjordjevicTT For a workaround, I assume we can force a row-major layout, which is expected to work. However, I'm not sure is this is the right path to go. 

To be certain, I opened an "bug" on tt-metal repo as well in order to gather more details around embedding op:
- https://github.com/tenstorrent/tt-metal/issues/12644

**Comment by sdjordjevicTT** [comment] 2024-09-13 15:45
Yeah, we can work around it by forcing a row-major layout. I agree, let's see what metal folks say about the issue first...

**Comment by nvukobratTT** [comment] 2024-09-24 06:24
This issue is blocked by this one as well:
- https://github.com/tenstorrent/tt-metal/issues/12866

Marking it in blocking field.

**Comment by nvukobratTT** [comment] 2024-10-07 16:24
@sdjordjevicTT @mtopalovicTT hey guys, looks like reshape PR on TTNN is merged 🎉 

Can you look into uplifting Metal to the latest version, so we can unblock Llama sooner rather than latter. Also, I saw @jserbedzijaTT is doing uplift right now, maybe it'll be good to catch this one as well ;))

**Comment by sdjordjevicTT** [comment] 2024-10-17 19:47
We tried the reshape, but the uplift failed on the embedding test. There is some regression related to the fix, hence @mtopalovicTT raised an issue on the metal side:
https://github.com/tenstorrent/tt-metal/issues/13799

**Comment by sdjordjevicTT** [comment] 2024-11-13 10:56
I belive we can close this one now. The fix should be in...

**Closed** 2024-11-13 10:57 UTC
