### ISSUE TITLE
[StableHLO] reshape op failure for multi dimensional reshaping

### ISSUE THREAD

**Issue by mmanzoorTT** [tenstorrent/tt-mlir#1344] opened 2024-11-20 15:13 UTC
`stablehlo.reshape` conversion is failing if we reshape multiple dimensions simultaneously. 

An example stablehlo graph
```
module {
  func.func @main(%arg0: tensor<1x3x256x256xbf16>) -> tensor<1x3x16x16x16x16xbf16> {
    %0 = stablehlo.reshape %arg0 : (tensor<1x3x256x256xbf16>) -> tensor<1x3x16x16x16x16xbf16>
    return %0 : tensor<1x3x16x16x16x16xbf16>
  }
}
```

Error message
```
results/mlir_tests/stable_hlo/aten::view_0.mlir:3:10: error: 'ttir.reshape' op Shape attribute must have at most 5 elements	"results/mlir_tests/stable_hlo/aten::view_0.mlir:3:10: error: 'ttir.reshape' op Shape attribute must have at most 5 elements
    %0 = stablehlo.reshape %arg0 : (tensor<1x3x256x256xbf16>) -> tensor<1x3x16x16x16x16xbf16>
         ^
results/mlir_tests/stable_hlo/aten::view_0.mlir:3:10: note: see current operation: %1 = ""ttir.reshape""(%arg0, %0) <{operand_constraints = [#tt.operand_constraint<dram|l1|tile|none|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device_tile>, #tt.operand_constraint<dram|l1|tile|none|interleaved|single_bank|height_sharded|width_sharded|block_sharded|any_layout|any_device_tile>], shape = [1 : i32, 3 : i32, 16 : i32, 16 : i32, 16 : i32, 16 : i32]}> : (tensor<1x3x256x256xbf16>, tensor<1x3x16x16x16x16xbf16>) -> tensor<1x3x16x16x16x16xbf16>
```

**Comment by ajakovljevicTT** [comment] 2024-11-21 13:53
I did some initial digging into this bug, putting notes below:
The reshape op in `tt-metal` currently does not support tensors with more that 4 dimensions with tile layout (issue https://github.com/tenstorrent/tt-metal/issues/13889). However, that is currently being fixed (https://github.com/tenstorrent/tt-metal/commit/d08a9fcd27d3b6381cd720f37bd5741158cc6fcb). I cherry-picked this commit manually to our version of metal, disabled the asserts and ran the test above. It passed, with a small caveat. Since reshape puts out the view of a tensor, and does not change the tensor memory place itself, that means that we will need to change how we do deallocation op on our side (as it will lead to deallocating twice in the current setup).

Should we wait for the PR on metal to see if the issues go away? @mmanzoorTT @mrakitaTT

**Comment by mmanzoorTT** [comment] 2024-11-21 15:28
Thanks @ajakovljevicTT . We have to wait till next tt-metal uplift to resolve this problem. You may open a tt-metal issue to describe the problem and get their feedback in meanwhile.

**Comment by jvegaTT** [comment] 2024-12-05 03:47
The pr in tt-metal was just merged, can you verify if the issue is solved?

**Comment by ajakovljevicTT** [comment] 2024-12-05 08:37
> The pr in tt-metal was just merged, can you verify if the issue is solved?

Will do that, thanks!

**Comment by ajakovljevicTT** [comment] 2024-12-05 14:35
Update: I have manually uplifted new `tt-metal` main and disabled the asserts in `tt-mlir` and the code above works. However, the newest version of `tt-metal` is not uplifted due to some compilation issues (PR https://github.com/tenstorrent/tt-mlir/pull/1512). I have pushed the fix to the uplift branch, and hopefully the uplift will be soon merged into main.

**Comment by ajakovljevicTT** [comment] 2024-12-06 14:48
The tt-metal uplift has been merged and I have tested that the new reshape works with more than 4D tensors. The PR which will allow this on our side is here: https://github.com/tenstorrent/tt-mlir/pull/1524

**Comment by ajakovljevicTT** [comment] 2024-12-09 12:27
Closed by https://github.com/tenstorrent/tt-mlir/pull/1524

**Closed by ajakovljevicTT** 2024-12-09 12:27 UTC
Labels: stablehlo conversion bug
